export const cards = {
    GET_CARDS_START: "GET_CARDS_START",
    GET_CARDS_SUCCESS: "GET_CARDS_SUCCESS",
    GET_CARDS_FAIL: "GET_CARDS_FAIL",

    ADD_CARD_START: "ADD_CARD_START",
    ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
    ADD_CARD_FAIL: "ADD_CARD_FAIL",

    EDIT_CARD_START: "EDIT_CARD_START",
    EDIT_CARD_SUCCESS: "EDIT_CARD_SUCCESS",
    EDIT_CARD_FAIL: "EDIT_CARD_FAIL",

    SORT_CARDS_START: "SORT_CARDS_START",
    SORT_CARDS_SUCCESS: "SORT_CARDS_SUCCESS",
    SORT_CARDS_FAIL: "SORT_CARDS_FAIL",
};

export const LOGIN = 'LOGIN';